доработана функциональность по ТЗ спринта 6
mrchcat/java-kanban pull request #1
Opened 2024-03-08 14:19 UTC by mrchcat

feat: доработать HistoryManager (реализовать аналог LinkedHashMap)
test: написать тесты для HistoryManager
refactor: оптимизировать тесты для TaskManager

2024-03-08 16:25 UTC, mrchcat commented
feature: доработать HistoryManager (бесконечная емкость, проверяет на повторы, поднимает вверх недавно просмотренные задачи)
test: доработаны тесты с учетом изменений

2024-03-09 08:24 UTC, kalitva requested changes

2024-03-09 08:24 UTC, kalitva commented on .gitignore
> +# добавлено мной
Не нужен этот коммент

2024-03-09 08:24 UTC, kalitva commented on src/enums/Status.java
> -package ru.yandex.practicum.taskmanager.enums;
А зачем переименован пакет? Было же правильно по конвенции

https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

Нужно вернуть обратно (для всех пакетов)

2024-03-09 08:24 UTC, kalitva commented on src/enums/Status.java
> +package enums;
Для энамов не нужен отдельный пакет, положи где лежат задачи

2024-03-09 08:24 UTC, kalitva commented on src/enums/Type.java
>  public enum Type {
Не понятно тип чего? Нужно уточнить в названии класса (shift + f6 чтобы переименовать)

2024-03-09 08:24 UTC, kalitva commented on src/service/RegularTaskManager.java
> +    private final HistoryManager history; // хранилище списка просмотренных задач
Этот и комменты выше не нужны

2024-03-09 08:24 UTC, kalitva commented on src/service/RegularTaskManager.java
> +        if (task == null) return null;
Всегда оборачивай тело условий и циклов в фигурные скобки, даже для одного стэйтмента

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2024-03-09 08:24 UTC, kalitva commented on src/service/RegularTaskManager.java
>              default -> throw new IllegalArgumentException("Некорректный статус задачи");
Сообщения исключений только по английски

2024-03-09 08:24 UTC, kalitva commented on src/tasks/Epictask.java
>  public class Epictask extends Task {
`Epictask --> Epic`

Переименуй

2024-03-09 08:24 UTC, kalitva commented on src/tasks/Task.java
>          return id.hashCode();
Может вылетиеь NPE

2024-03-09 08:24 UTC, kalitva commented on src/utils/LinkedHashHistoryManager.java
> +    final HashMap<Integer, Node> nodes;
private

2024-03-09 08:24 UTC, kalitva commented on src/utils/LinkedHashHistoryManager.java
> +        if (nodes.containsKey(id)) {
```java
if (!nodes.containsKey(id)) {
    return;
}
Node cur = nodes.get(id);
Node beforeCur = cur.before;
Node afterCur = cur.next;
beforeCur.next = afterCur;
if (afterCur != null) {
    afterCur.before = beforeCur;
}
nodes.remove(id);
```

Используй guard clause чтобы обойтись без лишней вложенности

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2024-03-09 08:24 UTC, kalitva commented on src/utils/LinkedHashHistoryManager.java
> +        else {
`else` не нужен

2024-03-09 08:24 UTC, kalitva commented on test/service/ManagersTest.java
> +    @DisplayName("получить класс TaskManager")
Лучше по английски

2024-03-10 10:22 UTC, kalitva approved these changes

2024-03-10 10:22 UTC, kalitva commented on src/ru/yandex/practicum/taskmanager/service/RegularTaskManager.java
> +        if (task == null) return null;
Пожалуйста, везде скобочки для условных выражений

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

Проверь везде, это обязательно

2024-03-10 10:22 UTC, kalitva commented on src/ru/yandex/practicum/taskmanager/service/RegularTaskManager.java
>      public Task delete(Integer idToDelete) {
`idToDelete --> taskId`

shift + F6 чтобы переименовать в intellij

2024-03-10 10:22 UTC, kalitva commented on test/service/ManagersTest.java
> +package service;
Тестовый класс в должен лежать в том же пакете, что и тестируемый (но в другом каталоге `test`)

2024-03-10 10:22 UTC, kalitva commented on test/utils/LinkedHashHistoryManagerTest.java
> +    void AddFirstTest() {
А чего с большой буквы?

https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names

Тестовых методов также касается

2024-03-10 17:01 UTC, merged